spring:
  profiles:
    active: dev
    
---

spring:
  batch:
    jdbc.initialize-schema: ALWAYS
    job:
      enabled: false
  config.activate.on-profile: dev
  output.ansi.enabled: ALWAYS
  jpa:
    show_sql: true
    hibernate:
        ddl_auto: validate
  datasource:
      url: jdbc:mysql://localhost:3306/biblio
      username: root
      password: root
