
spring:
  config.activate.n-profile: dev
  output.ansi.enabled: ALWAYS

  jpa:
    show_sql: true
    hibernate:
        ddl_auto: update
  datasource:
      url: jdbc:mysql://localhost:3306/biblio
      username: root
      password: root

